MGurtD/lilith-backend

Api/Controllers/Production/WorkMasterController.cs, Api/Controllers/Shared/ReferenceController.cs, Application/Persistance/IUnitOfWork.cs, Application/Persistance/Repositories/Production/IWorkMasterPhaseRepository.cs, Application/Persistance/Repositories/Production/IWorkMasterRepository.cs, Domain/Entities/Production/WorkMaster.cs, Domain/Entities/Production/WorkMasterPhase.cs, Domain/Entities/Production/WorkMasterPhaseBillOfMaterials.cs, Domain/Entities/Production/WorkMasterPhaseDetail.cs, Infrastructure/Migrations/20231124172810_Fix_WorkMasterEntitiesErrors.Designer.cs, Infrastructure/Migrations/20231124172810_Fix_WorkMasterEntitiesErrors.cs, Infrastructure/Migrations/20231125175159_Fix_WorkMasterEntitiesErrors_2.Designer.cs, Infrastructure/Migrations/20231125175159_Fix_WorkMasterEntitiesErrors_2.cs, Infrastructure/Persistance/Repositories/Production/WorkMasterPhaseRepository.cs, Infrastructure/Persistance/Repositories/Production/WorkMasterRepository.cs, Infrastructure/Persistance/UnitOfWork.cs
- Workmaster and child entities domain entities
- Workmaster and child entities database mapping
- Workmaster controller
=> Workmaster management

Api/Controllers/Warehouse/WarehouseController.cs, Api/Services/ReceiptRepository.cs, Api/Services/StockMovementService.cs, Domain/Entities/Warehouse/Location.cs, Domain/Entities/Warehouse/Warehouse.cs, Infrastructure/Migrations/20231127153018_Refactor_WarehouseDefaultLocation.Designer.cs, Infrastructure/Migrations/20231127153018_Refactor_WarehouseDefaultLocation.cs, Infrastructure/Persistance/EntityConfiguration/Warehouse/LocationBuilder.cs, Infrastructure/Persistance/EntityConfiguration/Warehouse/WarehouseBuilder.cs
fixed: warehouse controller location methods
=> changed: default location into warehouse

Api/Controllers/Purchase/ReceiptController.cs, Api/Services/Purchase/ReceiptService.cs, Application/Services/Purchase/IReceiptService.cs, Domain/Entities/Purchase/Receipt.cs, Domain/Repositories/Purchase/IPurchaseInvoiceRepository.cs, Infrastructure/Migrations/20240213174128_Add_ReceiptAndPurchaseInvoiceRelationship.Designer.cs, Infrastructure/Migrations/20240213174128_Add_ReceiptAndPurchaseInvoiceRelationship.cs
Story details: https://app.shortcut.com/zenith-1/story/55
=> feat: [sc-55] Traçabilitat documents de compra

Api/Controllers/Production/ProductionPartController.cs, Api/Controllers/Production/WorkOrderController.cs, Application/Contracts/Production/DetailedWorkOrder.cs, Application/Persistance/IUnitOfWork.cs, Domain/Entities/Production/ProductionPart.cs, Domain/Entities/Production/WorkOrder.cs, Domain/Repositories/Production/IProductionPartRepository.cs, Domain/Repositories/Production/IWorkOrderRepository.cs, Infrastructure/Migrations/20240219171712_create_view_detailedworkorder.Designer.cs, Infrastructure/Migrations/20240219171712_create_view_detailedworkorder.cs, Infrastructure/Migrations/20240220175703_Add_WorkOrderAndWorkOrderPhaseToProductionParts.Designer.cs, Infrastructure/Migrations/20240220175703_Add_WorkOrderAndWorkOrderPhaseToProductionParts.cs, Infrastructure/Migrations/20240226173944_Add_CostsToWorkOrder.Designer.cs, Infrastructure/Migrations/20240226173944_Add_CostsToWorkOrder.cs, Infrastructure/Persistance/ApplicationDbContext.cs, Infrastructure/Persistance/EntityConfiguration/Production/WorkOrderBuilder.cs, Infrastructure/Persistance/Repositories/Production/ProductionPartRepository.cs, Infrastructure/Persistance/Repositories/Production/WorkOrderRepository.cs, Infrastructure/Persistance/UnitOfWork.cs
Story details: https://app.shortcut.com/zenith-1/story/45
=> feat: [sc-45] Production tickets

Api/Controllers/Production/ProductionPartController.cs, Api/Controllers/Production/WorkOrderController.cs
Story details: https://app.shortcut.com/zenith-1/story/66
=> feat: [sc-66] Costos operari i costos maquina

Api/Controllers/Production/WorkOrderController.cs, Api/Services/Production/WorkOrderService.cs, Application/Services/Production/IWorkOrderService.cs
Story details: https://app.shortcut.com/zenith-1/story/92
=> feat: [sc-92] Crear nou formulari introducció de tiquets desde la OF

Api/Controllers/Shared/ReferenceController.cs, Domain/Entities/Shared/Reference.cs, Infrastructure/Migrations/20240501094509_Add_CustomerToReferences.Designer.cs, Infrastructure/Migrations/20240501094509_Add_CustomerToReferences.cs
Story details: https://app.shortcut.com/zenith-1/story/145
=> feat: [sc-145] Afegir Camp de Client a les Referències

Api/Services/Production/WorkOrderService.cs, Domain/Entities/Production/ProductionPart.cs, Infrastructure/Migrations/20240621074118_Add workcenter time to production part.Designer.cs, Infrastructure/Migrations/20240621074118_Add workcenter time to production part.cs, Infrastructure/Persistance/EntityConfiguration/Production/ProductionPartBuilder.cs
Story details: https://app.shortcut.com/zenith-1/story/182
=> fix: [sc-182] Al introduir un tíquet de producció el temps es fa servir pel cost de màquina i d' operari

Api/Controllers/Production/PlanningController.cs, Domain/Entities/Production/Workcenter.cs
Story details: https://app.shortcut.com/zenith-1/story/157
=> feat: [sc-157] Desenvolupar la Primera Maqueta de la Pantalla de Detall del Centre de Treball

Api/Controllers/Auth/UserFilterController.cs, Api/Services/Sales/SalesOrderService.cs, Application/Persistance/IUnitOfWork.cs, Domain/Entities/Auth/UserFilter.cs, Infrastructure/Migrations/20240712140506_Add_UserFilters.Designer.cs, Infrastructure/Migrations/20240712140506_Add_UserFilters.cs, Infrastructure/Persistance/EntityConfiguration/Auth/UserFilterBuilder.cs, Infrastructure/Persistance/UnitOfWork.cs
Story details: https://app.shortcut.com/zenith-1/story/199
=> feat: [sc-199] Guardar filtres a les diferents pàgines

Api/Controllers/Purchase/ExpenseController.cs, Api/Controllers/Sales/SalesInvoiceController.cs, Api/Services/Sales/SalesInvoiceService.cs, Application/Contracts/Sales/CreateRectificativeInvoiceRequest.cs, Application/Services/Sales/ISalesInvoiceService.cs, Domain/Entities/Sales/SalesInvoice.cs, Infrastructure/Migrations/20240721173039_Add_ParentSalesInvoiceRelation.Designer.cs, Infrastructure/Migrations/20240721173039_Add_ParentSalesInvoiceRelation.cs
Story details: https://app.shortcut.com/zenith-1/story/252
=> feat: [sc-252] Afegir filtres de data a les despeses

Api/Controllers/Sales/SalesInvoiceController.cs, Api/Services/Sales/SalesInvoiceService.cs, Application/Contracts/Sales/CreateRectificativeInvoiceRequest.cs, Application/Services/Sales/ISalesInvoiceService.cs, Domain/Entities/Sales/SalesInvoice.cs, Infrastructure/Migrations/20240721173039_Add_ParentSalesInvoiceRelation.Designer.cs, Infrastructure/Migrations/20240721173039_Add_ParentSalesInvoiceRelation.cs
Story details: https://app.shortcut.com/zenith-1/story/191
=> feat: [sc-191] Crear factura rectificativa

Api/Controllers/Production/ProductionCostController.cs, Application/Contracts/Production/ProductionCost.cs, Application/Persistance/IUnitOfWork.cs, Infrastructure/Migrations/20240814093733_ADD View Production Costs.Designer.cs, Infrastructure/Migrations/20240814093733_ADD View Production Costs.cs, Infrastructure/Persistance/ApplicationDbContext.cs, Infrastructure/Persistance/UnitOfWork.cs
Story details: https://app.shortcut.com/zenith-1/story/265
=> feat: [sc-265] Dashboard Costos per tipus de centre de treball

Api/Controllers/Purchase/PurchaseOrderController.cs, Api/Services/Purchase/PurchaseOrderService.cs, Application/Contracts/Purchase/PurchaseOrderReportResponse.cs, Application/Services/Purchase/IPurchaseOrderService.cs, Domain/Entities/Purchase/PurchaseOrder.cs
Story details: https://app.shortcut.com/zenith-1/story/277
=> feat: [sc-277] Informe comanda de compra

Domain/Entities/Shared/Reference.cs, Infrastructure/Migrations/20240925072849_Add AreaId to reference.Designer.cs, Infrastructure/Migrations/20240925072849_Add AreaId to reference.cs
Story details: https://app.shortcut.com/zenith-1/story/297
=> feat: [sc-297] Referència de tipus eina, afegir area (label àrea de producció)

Domain/Entities/Sales/BudgetDetail.cs, Domain/Entities/Sales/SalesOrderDetail.cs, Infrastructure/Migrations/20241008093711_AddDetailedProfitAndCostFields.Designer.cs, Infrastructure/Migrations/20241008093711_AddDetailedProfitAndCostFields.cs, Infrastructure/Persistance/EntityConfiguration/Sales/BudgetDetailBuilder.cs, Infrastructure/Persistance/EntityConfiguration/Sales/SalesOrderDetailBuilder.cs
Story details: https://app.shortcut.com/zenith-1/story/324
=> feat: [sc-324] Comanda / pressupost calculadora. Repensar els percentatges !!!!

Api/Controllers/Shared/ReferenceController.cs
Story details: https://app.shortcut.com/zenith-1/story/322
=> fix: [sc-322] Comanda 24108 - Ordenació de linies per referencies no funciona

Api/Services/Sales/DeliveryNoteService.cs
Story details: https://app.shortcut.com/zenith-1/story/353
=> fix: [sc-353] Al guardar un albarà com  a entregat, la data d'entrega es sobreescriu per la data actual

Api/Services/Purchase/PurchaseOrderService.cs, Api/Services/Sales/SalesOrderService.cs, Domain/Repositories/Purchase/IPurchaseOrderRepository.cs, Infrastructure/Persistance/Repositories/Purchase/PurchaseOrderRepository.cs
Story details: https://app.shortcut.com/zenith-1/story/320
=> fix: [sc-320] Eliminar la comanda de compra, falla.

Api/Controllers/Sales/SalesInvoiceController.cs, Api/Services/Sales/SalesInvoiceService.cs, Application/Services/Sales/ISalesInvoiceService.cs, Domain/Repositories/Sales/ISalesInvoiceRepository.cs, Infrastructure/Persistance/Repositories/Sales/SalesInvoiceRepository.cs
Story details: https://app.shortcut.com/zenith-1/story/357
=> feat: [sc-357] Permetre fer factures amb linies lliures en negatiu

Api/Controllers/Purchase/PurchaseInvoiceController.cs, Api/Controllers/Sales/SalesInvoiceController.cs, Api/Services/Purchase/PurchaseInvoiceService.cs, Api/Services/Sales/SalesInvoiceService.cs, Application/Contracts/Purchase/ChangeStatusOfInvoicesRequest.cs, Application/Services/Purchase/IPurchaseInvoiceService.cs, Application/Services/Sales/ISalesInvoiceService.cs
Story details: https://app.shortcut.com/zenith-1/story/325
=> feat: [sc-325] Factures de venta - Accés gestoria

Api/Middlewares/HttpLoggingMiddleware.cs, Api/Program.cs, Domain/Entities/Logger/HttpTransactionLog.cs, Infrastructure/Migrations/20241025070400_AddNewSchemaAudit.Designer.cs, Infrastructure/Migrations/20241025070400_AddNewSchemaAudit.cs, Infrastructure/Persistance/ApplicationDbContext.cs, Infrastructure/Persistance/EntityConfiguration/Logger/HttpTransactionLogBuilder.cs
Story details: https://app.shortcut.com/zenith-1/story/355
=> feat: [sc-355] Afegir logger per veure temps d'execució

Api/Configuration.cs, Api/Program.cs, Api/Services/Purchase/PurchaseOrderService.cs
Story details: https://app.shortcut.com/zenith-1/story/352
=> feat: [sc-352] Report comanda de compra. Agrupar per codi i descripció

Api/Controllers/Purchase/PurchaseInvoiceController.cs, Api/Services/Purchase/PurchaseOrderService.cs
Story details: https://app.shortcut.com/zenith-1/story/381
=> feat: [sc-381] Compra - Associar albarans a factura
